version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:47"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
