load("@rules_kotlin//kotlin:core.bzl", "kt_kotlinc_options")

package(default_visibility = ["//visibility:private"])

exports_files(["maven_install.json"])

kt_kotlinc_options(
    name = "kotlin_options",
    jvm_target = "25",
    visibility = ["//systems/xquare-platform:__pkg__"],
    x_annotation_default_target = "param-property",
    x_jspecify_annotations = "strict",
)
