module(
    name = "xquare_platform",
)

bazel_dep(name = "aspect_rules_js", version = "3.2.2")
bazel_dep(name = "rules_java", version = "9.3.0")
bazel_dep(name = "rules_jvm_external", version = "7.0")
bazel_dep(name = "rules_kotlin", version = "2.3.20")
bazel_dep(name = "rules_go", version = "0.61.1")
bazel_dep(name = "rules_nodejs", version = "6.7.4")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.26.4")

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(node_version = "24.14.1")

include("//build/jvm:java_deps.MODULE.bazel")
