load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary", "kt_jvm_library")

package(default_visibility = ["//visibility:private"])

kt_jvm_library(
    name = "xquare_platform",
    srcs = ["XquarePlatformApplication.kt"],
    kotlinc_opts = "//systems/xquare-platform:kotlin_options",
    resources = ["//systems/xquare-platform/src/main/resources:application.yml"],
    visibility = ["//systems/xquare-platform/src/test/kotlin/kr/dsm/hs/xquare/platform:__pkg__"],
    runtime_deps = [
        "@jvm_maven//:org_jetbrains_kotlin_kotlin_reflect",
        "@jvm_maven//:org_springframework_boot_spring_boot_starter_webmvc",
    ],
    deps = [
        "@jvm_maven//:org_springframework_boot_spring_boot",
        "@jvm_maven//:org_springframework_boot_spring_boot_autoconfigure",
    ],
)

kt_jvm_binary(
    name = "xquare_platform_app",
    srcs = ["Main.kt"],
    kotlinc_opts = "//systems/xquare-platform:kotlin_options",
    main_class = "kr.dsm.hs.xquare.platform.MainKt",
    visibility = ["//systems/xquare-platform:__pkg__"],
    deps = [
        ":xquare_platform",
        "@jvm_maven//:org_springframework_boot_spring_boot",
    ],
)
