load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//visibility:private"])

kt_jvm_library(
    name = "domain",
    srcs = glob(
        ["*.kt"],
        allow_empty = True,
    ),
    kotlinc_opts = "//systems/xquare-application:kotlin_options",
    visibility = [
        "//systems/xquare-application/xquare-application-ticket/src/main/kotlin/kr/dsm/hs/xquare/ticket/adapter:__pkg__",
        "//systems/xquare-application/xquare-application-ticket/src/main/kotlin/kr/dsm/hs/xquare/ticket/application:__pkg__",
    ],
)
