load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")
load("//systems/xquare-application/lint:linters.bzl", "ktlint_test")

package(default_visibility = ["//visibility:private"])

kt_jvm_test(
    name = "xquare_application_test",
    size = "small",
    srcs = ["XquareApplicationTest.kt"],
    args = [
        "execute",
        "--disable-banner",
        "--select-class=kr.dsm.hs.xquare.application.XquareApplicationTest",
    ],
    kotlinc_opts = "//systems/xquare-application:kotlin_options",
    main_class = "org.junit.platform.console.ConsoleLauncher",
    runtime_deps = [
        "@jvm_maven//:org_junit_jupiter_junit_jupiter_engine",
        "@jvm_maven//:org_junit_platform_junit_platform_console",
        "@jvm_maven//:org_springframework_boot_spring_boot_starter_test",
    ],
    deps = [
        "//systems/xquare-application/src/main/kotlin/kr/dsm/hs/xquare/application:xquare_application_lib",
        "@jvm_maven//:org_junit_jupiter_junit_jupiter_api",
        "@jvm_maven//:org_springframework_boot_spring_boot_test",
    ],
)

ktlint_test(
    name = "xquare_application_test_ktlint_test",
    size = "small",
    srcs = [":xquare_application_test"],
)
