bazel_dep(name = "aspect_rules_lint", version = "2.6.0")

ktlint = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

ktlint(
    name = "xquare_application_ktlint",
    executable = True,
    sha256 = "a3fd620207d5c40da6ca789b95e7f823c54e854b7fade7f613e91096a3706d75",
    urls = ["https://github.com/ktlint/ktlint/releases/download/1.8.0/ktlint"],
)

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    name = "jvm_maven",
    artifacts = [],
    duplicate_version_warning = "error",
    fail_if_repin_required = True,
    fail_on_missing_checksum = True,
    fetch_sources = True,
    lock_file = "//systems/xquare-application:maven_install.json",
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
    strict_visibility = True,
    version_conflict_policy = "pinned",
)
maven.from_toml(
    name = "jvm_maven",
    bom_modules = [
        "org.springframework.boot:spring-boot-dependencies",
    ],
    libs_versions_toml = "//systems/xquare-application:deps.toml",
)
maven.override(
    name = "jvm_maven",
    coordinates = "org.jetbrains.kotlin:kotlin-stdlib",
    target = "@rules_kotlin//kotlin/compiler:kotlin-stdlib",
)
maven.override(
    name = "jvm_maven",
    coordinates = "org.jetbrains.kotlin:kotlin-stdlib-jdk7",
    target = "@rules_kotlin//kotlin/compiler:kotlin-stdlib-jdk7",
)
maven.override(
    name = "jvm_maven",
    coordinates = "org.jetbrains.kotlin:kotlin-stdlib-jdk8",
    target = "@rules_kotlin//kotlin/compiler:kotlin-stdlib-jdk8",
)
use_repo(maven, "jvm_maven")
