load("@rules_kotlin//kotlin:core.bzl", "kt_kotlinc_options")

package(default_visibility = ["//visibility:private"])

exports_files([
    "deps.toml",
    "maven_install.json",
])

exports_files(
    [
        ".editorconfig",
        "ktlint-baseline.xml",
    ],
    visibility = ["//systems/xquare-application:__subpackages__"],
)

kt_kotlinc_options(
    name = "kotlin_options",
    jvm_target = "25",
    visibility = ["//systems/xquare-application:__subpackages__"],
    x_annotation_default_target = "param-property",
    x_jspecify_annotations = "strict",
)

alias(
    name = "xquare_application",
    actual = "//systems/xquare-application/xquare-application-infrastructure/src/main/kotlin/kr/dsm/hs/xquare/infrastructure:xquare_application",
)
