load("@rules_kotlin//kotlin:core.bzl", "kt_kotlinc_options")

package(default_visibility = ["//visibility:private"])

kt_kotlinc_options(
    name = "kotlin_options",
    jvm_target = "25",
    visibility = [
        "//systems/xquare-platform/src/main/kotlin/kr/dsm/hs/xquare/platform:__pkg__",
        "//systems/xquare-platform/src/test/kotlin/kr/dsm/hs/xquare/platform:__pkg__",
    ],
    x_annotation_default_target = "param-property",
    x_jspecify_annotations = "strict",
)

alias(
    name = "xquare_platform_app",
    actual = "//systems/xquare-platform/src/main/kotlin/kr/dsm/hs/xquare/platform:xquare_platform_app",
)
