load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary", "kt_jvm_library", "kt_jvm_test")

package(default_visibility = ["//visibility:private"])

kt_jvm_library(
    name = "xquare_platform",
    srcs = ["src/main/kotlin/kr/dsm/hs/xquare/platform/XquarePlatformApplication.kt"],
    kotlinc_opts = "//:kotlin_options",
    resources = ["src/main/resources/application.yml"],
    runtime_deps = [
        "@maven//:org_jetbrains_kotlin_kotlin_reflect",
        "@maven//:org_springframework_boot_spring_boot_starter_webmvc",
    ],
    deps = [
        "@maven//:org_springframework_boot_spring_boot",
        "@maven//:org_springframework_boot_spring_boot_autoconfigure",
    ],
)

kt_jvm_binary(
    name = "xquare_platform_app",
    srcs = ["src/main/kotlin/kr/dsm/hs/xquare/platform/Main.kt"],
    kotlinc_opts = "//:kotlin_options",
    main_class = "kr.dsm.hs.xquare.platform.MainKt",
    deps = [
        ":xquare_platform",
        "@maven//:org_springframework_boot_spring_boot",
    ],
)

kt_jvm_test(
    name = "xquare_platform_test",
    size = "small",
    srcs = ["src/test/kotlin/kr/dsm/hs/xquare/platform/XquarePlatformApplicationTest.kt"],
    args = [
        "execute",
        "--disable-banner",
        "--select-class=kr.dsm.hs.xquare.platform.XquarePlatformApplicationTest",
    ],
    kotlinc_opts = "//:kotlin_options",
    main_class = "org.junit.platform.console.ConsoleLauncher",
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_console",
        "@maven//:org_springframework_boot_spring_boot_starter_test",
    ],
    deps = [
        ":xquare_platform",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_springframework_boot_spring_boot_test",
    ],
)
